"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
 the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum
of the even-valued terms."""

from functools import lru_cache


@lru_cache()
def fib(n):
    if n == 0:
        return 1

    if n == 1:
        return 2

    return fib(n-1) + fib(n-2)

if __name__ == '__main__':
    sum_ = 0
    for i in range(1, 1000000):
        f = fib(i)

        if f > 4000000:
            break

        if f %2 == 0:
            sum_ += f

    print(sum_)
