"""The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"""

from collections import Counter

from primes import prime_factorization

def numberofdivisors(n):
    if n == 1:
        return 1
    pf = prime_factorization(n)
    lookup = Counter(pf)
    numDivisors = 1
    for val in lookup.values():
        numDivisors *= (val + 1)
    return numDivisors

assert (numberofdivisors(1) == 1)
assert (numberofdivisors(2) == 2)
assert (numberofdivisors(3) == 2)
assert (numberofdivisors(4) == 3)
assert (numberofdivisors(5) == 2)
assert (numberofdivisors(6) == 4)
assert (numberofdivisors(7) == 2)
assert (numberofdivisors(8) == 4)
assert (numberofdivisors(9) == 3)
assert (numberofdivisors(10) == 4)
assert (numberofdivisors(100) == 9)

n = 1
while True:
    triangle = (n * (n + 1)) / 2

    if numberofdivisors(triangle) >= 500:
        print(triangle)
        break
    n += 1
